config:
  validation: true
  warningsAsErrors: false

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

complexity:
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10
  LongMethod:
    ignoreAnnotated:
      - 'Composable'

# Compose Rules — io.nlopez.compose.rules:detekt
Compose:
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentSlotReused:
    active: true
  ContentTrailingLambda:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  RememberMissing:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
  PreviewPublic:
    active: true